# Generated by Django 5.1.7 on 2025-03-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temizliksite', '0002_photo_delete_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='star_rating',
            new_name='rating',
        ),
    ]
